import = [
    "~/.config/alacritty/themes/alacritty-theme/themes/catppuccin_frappe.toml"
]

[window]
dimensions = { columns = 220, lines = 50 }

[font]
normal = { family = "VictorMono Nerd Font", style = "Light" }
size = 15
