# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
a = 'workspace a'
o = 'workspace o'
e = 'workspace e'
u = 'workspace u'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
shift-a = 'move-node-to-workspace a'
shift-o = 'move-node-to-workspace o'
shift-e = 'move-node-to-workspace e'
shift-u = 'move-node-to-workspace u'
