# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
y = 'workspace Y'
i = 'workspace I'
x = 'workspace X'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
shift-y = 'move-node-to-workspace Y'
shift-i = 'move-node-to-workspace I'
shift-x = 'move-node-to-workspace X'
