#!/bin/bash
source "$CONFIG_DIR/colors.sh" # Loads all defined colors

ITEM_DIR="$CONFIG_DIR/items" # Directory where the items are configured
PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored

FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=3 # All paddings use this value (icon, label, background)

# Init clojure config
bb "$ITEM_DIR/config.clj"

# Setting up the general bar appearance of the bar
bar=(
  height=25
  color=$BAR_COLOR
  border_width=2
  border_color=$BAR_BORDER_COLOR
  shadow=off
  position=top
  sticky=on
  padding_right=10
  padding_left=10
  y_offset=4
  notch_offset=0
  topmost=window
  color=0x00000000
  border_color=0x00000000
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  icon.font="$FONT:Regular:14.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Semibold:13.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  label.shadow.drawing=on
  label.shadow.distance=2
  label.shadow.color=0xff000000
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=28
  background.corner_radius=9
  background.border_width=2
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
  scroll_texts=on

)

sketchybar --default "${defaults[@]}"

# Left
bb "$ITEM_DIR/spaces.clj"
bb "$ITEM_DIR/front_app.clj"

# Right
bb "$ITEM_DIR/calendar.clj"
bb "$ITEM_DIR/battery.clj"
bb "$ITEM_DIR/slack.clj"
bb "$ITEM_DIR/outlook.clj"
bb "$ITEM_DIR/mail.clj"

sketchybar --hotload on

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update
# Trigger custom events to init plugins
sketchybar --trigger aerospace_workspace_change

echo "sketchybar configuation loaded.."
