#!/bin/bash

source "$HOME/.config/borders/theme_colors.sh"

options=(
    style=round
    width=4.0
    hidpi=on
    active_color=$ACTIVE_COLOR
    inactive_color=$INACTIVE_COLOR
)

borders "${options[@]}"
